"""Fix OTP table

Revision ID: b2158b3b0db4
Revises: 82c425151316
Create Date: 2025-03-07 15:28:21.703204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2158b3b0db4'
down_revision: Union[str, None] = '82c425151316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('phone_number', sa.String(), nullable=False))
    op.drop_column('otps', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('otps', 'phone_number')
    # ### end Alembic commands ###
